### ISSUE TITLE
Remove redundant requires in ECO token

### ISSUE THREAD

**Issue by megaturbo** [Eco-Finance/ecofi#11]
In the `EcoFiToken.sol` both `transfer()` and `_transfer` starts with:
```solidity
require(_recipient != address(this), "cool message");
```

However `Eco.transfer` calls `super.transfer()` and `Eco._transfer` calls `super._transfer()` and the `ERC20.transfer` implementation (namely `super.transfer`) also calls `_transfer`.

So I would consider only overriding one of those to avoid confusion, hence removing one of the two `require`s.

**Comment by tshabs** [comment]
This is a mistake.  The Eco.transfer should be preventing transfer() to sproutContract (while still allowing transferFrom) whereas _transfer is preventing any kind of transfer to address(this) [Eco].  Both functions should be here, the require on Eco.transfer() is wrong.
