### ISSUE TITLE
"live updated" token balance & generation rate in frontend

### ISSUE THREAD

**Issue by tshabs** [Eco-Finance/ecofi#2]
The frontend needs to be able to display live balances & rates (like on aave.com), but obviously we cant call `balanceOf` every second (esp assuming most users will be going through metamask/infura where there are rate limits).
The way we achieve this is by reimplementing the rate/balance calculation in the frontend, when we first load the page we load the current balance and rate for the user, and then every second or so recalculate what the rate & balance would be (assuming the normal passing of time) and update the values on screen accordingly.
In order to see/test the generation rate increasing we might need a script to "fast forward" 90 days (where the generation bonus kicks in, causing the generation rate to go up a bit every second).

**Comment by tshabs** [comment]
While !8 is a good start, we actually need this to show live token balance (i.e more or less real time).  We should tick every second or so to recalculate current balance and show it (constantly updating) so that it shows SPRT balance in real time (we should also show live generation rate below this).

**Comment by roflolilolmao** [comment]
@tshabs It is already updating in real time; you'd need a few million staked tokens to see a change happening each second.

You can check out https://github.com/Eco-Finance/ecofi/pull/12 where I have changed the formatting so you can see the numbers with four decimals, which makes the updates more visible. Is this what you want?

Also, what do you mean about the live generation rate? Could you be more specific?

Thanks.

**Comment by tshabs** [comment]
It's an 18 decimal number we can show the whole thing (or just make it easy for web dev to choose how many decimals to display).

The generation rate also updates every second (as generation bonus grows).

We should be able to see Sprout Balance & Generation Rate update every second or so.
