### ISSUE TITLE
Improve gas analytics

### ISSUE THREAD

**Issue by tshabs** [Eco-Finance/ecofi#3]
Great suggestion from @megaturbo :

We can use this: https://hardhat.org/plugins/hardhat-gas-reporter.html

Which looks neat for gas analytics

However, this does not show the block time (as our current hacky gas reporter shows) which is useful for debugging tests as results depend on blocktime (for the calculation tests).   I do really like the hardhat-gas-reporter so maybe we keep our code, strip gas values & also use the hardhat-gas-reporter?

**Comment by 0xjac** [comment]
If the blocktime is only for debugging it should be logged with a debug level and hiddne by default because it clutters the output.

Or we make a custom reporter maybe?

**Comment by 0xjac** [comment]
Very second good point from @megaturbo if we have test which depend on blocktime then instead of logging it, we should test it and assert we have the block we expect!
