### ISSUE TITLE
Issues with blocktime in tests

### ISSUE THREAD

**Issue by tshabs** [Eco-Finance/ecofi#4]
Having multiple tests chained after one another, while convenient, seems to be causing some tests to fail randomly as there seems to be random 1-5 second delays between tests/transactions.  To [hopefully] avoid this maybe we can split all time sensitive tests up so they each start from fresh state .

**Comment by tshabs** [comment]
After thinking about this, I think we should use `evm_setNextBlockTimestamp` instead of `evm_increaseTime` to ensure tests don't fail (on a slow ci runner for eg)

**Comment by soullight** [comment]
Cool

Lawrence Lanoff
Acting Secretary
Ecofi incorporated
